import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/contexts/SocketContext";
import { RoomProvider } from "@/contexts/RoomContext";
import { UserProvider } from "@/contexts/UserContext";
import { MessageContextProvider } from "@/contexts/MessageContext";
import { GameContextProvider } from "@/contexts/GameContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <SocketProvider>
            <RoomProvider>
              <GameContextProvider>
                <MessageContextProvider>{children}</MessageContextProvider>
              </GameContextProvider>
            </RoomProvider>
          </SocketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
